channels:
  - r
  - intel
  - conda-forge
  - bioconda
  - BioBuilds
dependencies:
  - python=2.7.12
  - icu=54.1
  - r-base=3.4.1
  - r-seurat=1.4.0.16
  - pango=1.40.1
  - ncurses=5.9
  - harfbuzz=0.9.42
  - readline=6.2
  
  
